
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: DevOps/Docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=api.py
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: tapnearn
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: tapnearn_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
